"use client";

/*
  This page is fully client-side because it has an interactive form
  and computes results using JavaScript without needing a server.
*/

import { useState } from "react";
import { Lightbulb, Shield, TrendingUp, ArrowRight } from "lucide-react";

/*
  Platform stats derived from portfolio_insights.json generated by the Python pipeline.
  These numbers represent aggregated, k-anonymous metrics across all 3 clients
  running campaigns throughout 2024. Each number is traceable to a specific field
  in the pipeline output.

  avg_ctr_pct: from avg_ctr_by_platform
  cpm_median:  from cpm_ranges_by_platform
  avg_roas:    averaged from monthly_platform_roas across all 12 months of 2024
*/
const PLATFORM_DATA: Record<string, {
  avg_ctr_pct: number;
  cpm_median: number;
  avg_roas: number;
  cpm_min: number;
}> = {
  "Google Ads": {
    avg_ctr_pct: 3.973,
    cpm_median:  75.91,
    avg_roas:    4.14,
    cpm_min:     15.09,
  },
  "Meta Ads": {
    avg_ctr_pct: 2.483,
    cpm_median:  28.73,
    avg_roas:    7.14,
    cpm_min:     4.68,
  },
  "TikTok Ads": {
    avg_ctr_pct: 5.516,
    cpm_median:  49.48,
    avg_roas:    9.69,
    cpm_min:     9.11,
  },
};

/* The three ad platforms available in the portfolio */
const PLATFORMS = ["Google Ads", "Meta Ads", "TikTok Ads"];

/*
  A single recommendation entry: which platform, what percentage, how much money,
  what rank it received, and the explanation for why it was chosen.
*/
type PlatformRec = {
  platform: string;
  allocation_pct: number;
  budget_usd: number;
  rank: "Primary" | "Secondary" | "Supporting";
  reason: string;
  score: number;
  score_label: string;
};

/*
  Scores each platform based on the advertiser's goal, then returns
  the score and a plain-English label explaining what was measured.

  Brand Awareness: we want the most clicks per dollar of impression cost.
    Score = CTR divided by CPM (higher CTR per dollar = better reach value)

  More Conversions: we want the best return for every dollar spent.
    Score = average ROAS (how many dollars come back for each dollar in)

  Website Traffic: we want the most clicks, regardless of cost.
    Score = raw CTR percentage
*/
function scoreForGoal(platform: string, goal: string): { score: number; label: string } {
  const stats = PLATFORM_DATA[platform];
  if (goal === "awareness") {
    const score = stats.avg_ctr_pct / stats.cpm_median;
    return {
      score,
      label: `CTR/CPM ratio: ${score.toFixed(4)} (${stats.avg_ctr_pct.toFixed(2)}% CTR at $${stats.cpm_median.toFixed(2)} CPM)`,
    };
  }
  if (goal === "conversions") {
    return {
      score: stats.avg_roas,
      label: `Avg ROAS: ${stats.avg_roas.toFixed(2)}x (each $1 spent returns $${stats.avg_roas.toFixed(2)})`,
    };
  }
  /* Default: traffic - scored by raw CTR */
  return {
    score: stats.avg_ctr_pct,
    label: `Avg CTR: ${stats.avg_ctr_pct.toFixed(2)}% (this share of people who saw the ad clicked it)`,
  };
}

/*
  Adjusts a platform's score based on the target audience age.
  TikTok skews younger, so it gets a boost for under-25 audiences
  and a penalty for over-40 audiences where adoption is lower.
  Google gets a slight boost for older audiences who use search more.
*/
function applyAgeAdjustment(platform: string, score: number, age: string): number {
  if (age === "under25") {
    if (platform === "TikTok Ads")  return score * 1.20;
    if (platform === "Google Ads")  return score * 0.90;
  }
  if (age === "over40") {
    if (platform === "TikTok Ads")  return score * 0.70;
    if (platform === "Google Ads")  return score * 1.10;
    if (platform === "Meta Ads")    return score * 1.05;
  }
  return score;
}

/*
  Turns platform scores into allocation percentages based on the budget size.
  Smaller budgets concentrate more on fewer platforms so they don't spread
  too thin and become ineffective on any single channel.
*/
function buildAllocations(
  ranked: string[],
  budget: number
): Array<{ platform: string; pct: number; rank: PlatformRec["rank"] }> {
  if (budget < 5000) {
    /* Very small budget: only two platforms, majority goes to the top one */
    return [
      { platform: ranked[0], pct: 70, rank: "Primary"    },
      { platform: ranked[1], pct: 30, rank: "Secondary"  },
    ];
  }
  if (budget < 10000) {
    /* Mid budget: three platforms but still concentrated */
    return [
      { platform: ranked[0], pct: 60, rank: "Primary"    },
      { platform: ranked[1], pct: 30, rank: "Secondary"  },
      { platform: ranked[2], pct: 10, rank: "Supporting" },
    ];
  }
  /* Larger budget: more balanced across all three platforms */
  return [
    { platform: ranked[0], pct: 50, rank: "Primary"    },
    { platform: ranked[1], pct: 30, rank: "Secondary"  },
    { platform: ranked[2], pct: 20, rank: "Supporting" },
  ];
}

/*
  Generates a plain-English reason explaining why a platform received
  its particular allocation, grounded in the specific metric that drove it.
*/
function buildReason(platform: string, rank: PlatformRec["rank"], goal: string): string {
  const stats = PLATFORM_DATA[platform];
  if (rank === "Primary") {
    if (goal === "awareness")    return `Highest value for reach: ${stats.avg_ctr_pct.toFixed(2)}% CTR at a median CPM of $${stats.cpm_median.toFixed(2)} means you get the most clicks per dollar of impression spend.`;
    if (goal === "conversions")  return `Strongest return on spend: ${stats.avg_roas.toFixed(2)}x average ROAS means each dollar invested brings back $${stats.avg_roas.toFixed(2)} in revenue on average.`;
    return `Highest click rate: ${stats.avg_ctr_pct.toFixed(2)}% of people who see the ad click it, the highest of all three platforms.`;
  }
  if (rank === "Secondary") {
    if (goal === "awareness")    return `Good reach value as a secondary channel. CPM of $${stats.cpm_median.toFixed(2)} is within range and provides audience diversity.`;
    if (goal === "conversions")  return `Second-best ROAS at ${stats.avg_roas.toFixed(2)}x. Worth allocating budget here to diversify and reduce dependence on one platform.`;
    return `A reliable secondary traffic driver at ${stats.avg_ctr_pct.toFixed(2)}% CTR. Adds volume without too much extra cost.`;
  }
  /* Supporting */
  return `Use a small portion here to test performance and maintain presence. Data from 3 clients shows a CPM range of $${stats.cpm_min.toFixed(2)} to $${stats.cpm_median.toFixed(2)}.`;
}

/*
  The main recommendation function. Takes the form inputs and returns
  a list of platform recommendations sorted by allocation size.
*/
function computeRecommendation(
  goal: string,
  budget: number,
  audienceAge: string
): PlatformRec[] {
  /* Score each platform for the given goal */
  const scored = PLATFORMS.map((platform) => {
    const { score, label } = scoreForGoal(platform, goal);
    const adjusted = applyAgeAdjustment(platform, score, audienceAge);
    return { platform, score: adjusted, label };
  });

  /* Sort platforms by score, highest first */
  scored.sort((a, b) => b.score - a.score);
  const ranked = scored.map((s) => s.platform);

  /* Build allocation percentages */
  const allocs = buildAllocations(ranked, budget);

  /* Return the final list with all details filled in */
  return allocs.map((alloc) => {
    const scoreEntry = scored.find((s) => s.platform === alloc.platform)!;
    return {
      platform:       alloc.platform,
      allocation_pct: alloc.pct,
      budget_usd:     Math.round((alloc.pct / 100) * budget),
      rank:           alloc.rank,
      reason:         buildReason(alloc.platform, alloc.rank, goal),
      score:          scoreEntry.score,
      score_label:    scoreEntry.label,
    };
  });
}

/* Color dot for each platform, matching all other charts in the app */
const PLATFORM_COLORS: Record<string, string> = {
  "Meta Ads":   "#FF5656",
  "Google Ads": "#FF8A56",
  "TikTok Ads": "#F472B6",
};

/* Background color for each rank badge */
const RANK_STYLES: Record<PlatformRec["rank"], string> = {
  "Primary":    "bg-primary/10 text-primary border border-primary/20",
  "Secondary":  "bg-blue-50 text-blue-700 border border-blue-200",
  "Supporting": "bg-gray-100 text-gray-600 border border-gray-200",
};

/*
  The recommend page. Users fill out a short brand profile form and
  the system returns a data-driven channel allocation recommendation.
  Every recommendation is explained and traceable to specific numbers
  in the portfolio_insights.json pipeline output.
*/
export default function RecommendPage() {
  const [goal,        setGoal]        = useState("awareness");
  const [budget,      setBudget]      = useState("");
  const [audienceAge, setAudienceAge] = useState("25to40");
  const [brandName,   setBrandName]   = useState("");
  const [industry,    setIndustry]    = useState("");
  const [result,      setResult]      = useState<PlatformRec[] | null>(null);

  /* Run when the user clicks the Get Recommendation button */
  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const budgetNum = parseFloat(budget.replace(/[^0-9.]/g, ""));
    if (!budgetNum || budgetNum <= 0) return;
    const recs = computeRecommendation(goal, budgetNum, audienceAge);
    setResult(recs);
  }

  return (
    <div className="max-w-4xl mx-auto space-y-10">

      {/* Page header */}
      <div className="space-y-2">
        <div className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">
          Channel Recommendation Engine
        </div>
        <h1 className="text-3xl md:text-4xl font-semibold tracking-tight text-foreground">
          Find the right channel for{" "}
          <span className="text-gradient">your brand</span>
        </h1>
        <p className="text-sm text-muted-foreground max-w-2xl leading-relaxed">
          Enter your brand details below. The recommendation is calculated using
          anonymized performance data from 3 real clients running campaigns across
          Meta, Google, and TikTok throughout 2024. No guesswork - every suggestion
          is grounded in actual numbers from the portfolio pipeline.
        </p>
      </div>

      {/* Input form */}
      <form onSubmit={handleSubmit} className="surface-card rounded-xl p-6 space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">

          {/* Brand name input */}
          <div className="space-y-1.5">
            <label className="text-xs uppercase tracking-widest text-muted-foreground font-medium">
              Brand Name
            </label>
            <input
              type="text"
              value={brandName}
              onChange={(e) => setBrandName(e.target.value)}
              placeholder="e.g. Allagash Brewing"
              className="w-full px-3 py-2.5 rounded-lg border border-border bg-background text-foreground text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary/30 transition-colors placeholder:text-muted-foreground/50"
            />
          </div>

          {/* Industry input */}
          <div className="space-y-1.5">
            <label className="text-xs uppercase tracking-widest text-muted-foreground font-medium">
              Industry
            </label>
            <input
              type="text"
              value={industry}
              onChange={(e) => setIndustry(e.target.value)}
              placeholder="e.g. Sustainable food, Outdoor gear"
              className="w-full px-3 py-2.5 rounded-lg border border-border bg-background text-foreground text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary/30 transition-colors placeholder:text-muted-foreground/50"
            />
          </div>

          {/* Monthly budget input */}
          <div className="space-y-1.5">
            <label className="text-xs uppercase tracking-widest text-muted-foreground font-medium">
              Monthly Ad Budget (USD)
            </label>
            <input
              type="text"
              value={budget}
              onChange={(e) => setBudget(e.target.value)}
              placeholder="e.g. 10000"
              required
              className="w-full px-3 py-2.5 rounded-lg border border-border bg-background text-foreground text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary/30 transition-colors placeholder:text-muted-foreground/50"
            />
          </div>

          {/* Target audience age range */}
          <div className="space-y-1.5">
            <label className="text-xs uppercase tracking-widest text-muted-foreground font-medium">
              Target Audience Age
            </label>
            <div className="flex gap-2">
              {[
                { value: "under25", label: "Under 25" },
                { value: "25to40",  label: "25 to 40" },
                { value: "over40",  label: "Over 40"  },
              ].map((opt) => (
                <button
                  key={opt.value}
                  type="button"
                  onClick={() => setAudienceAge(opt.value)}
                  className={`flex-1 py-2 text-xs font-medium rounded-lg border transition-colors ${
                    audienceAge === opt.value
                      ? "bg-primary text-white border-primary"
                      : "bg-background text-muted-foreground border-border hover:border-primary/40"
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Primary campaign goal selector */}
        <div className="space-y-2">
          <label className="text-xs uppercase tracking-widest text-muted-foreground font-medium">
            Primary Campaign Goal
          </label>
          <div className="grid grid-cols-3 gap-3">
            {[
              { value: "awareness",    label: "Brand Awareness",  desc: "Maximize reach and visibility" },
              { value: "conversions",  label: "More Conversions", desc: "Drive sales and sign-ups"       },
              { value: "traffic",      label: "Website Traffic",  desc: "Get clicks to the site"         },
            ].map((opt) => (
              <button
                key={opt.value}
                type="button"
                onClick={() => setGoal(opt.value)}
                className={`p-4 rounded-xl border text-left transition-colors ${
                  goal === opt.value
                    ? "bg-primary/5 border-primary/30 text-primary"
                    : "bg-background border-border hover:border-primary/20"
                }`}
              >
                <div className="text-sm font-semibold mb-0.5">{opt.label}</div>
                <div className="text-xs text-muted-foreground">{opt.desc}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Submit button */}
        <button
          type="submit"
          className="w-full md:w-auto flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-primary text-white text-sm font-semibold hover:bg-primary/90 transition-colors"
        >
          Get Channel Recommendation
          <ArrowRight className="w-4 h-4" />
        </button>
      </form>

      {/* Recommendation result - only shows after the form is submitted */}
      {result && (
        <div className="space-y-6">

          {/* Result header */}
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg gradient-campfire flex items-center justify-center shrink-0">
              <Lightbulb className="w-4 h-4 text-white" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-foreground">
                {brandName ? `Recommendation for ${brandName}` : "Recommended Allocation"}
              </h2>
              <p className="text-xs text-muted-foreground">
                Based on 2024 portfolio data from 3 anonymized clients
              </p>
            </div>
          </div>

          {/* One card per platform in the recommendation */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {result.map((rec) => (
              <div
                key={rec.platform}
                className="surface-card rounded-xl p-5 space-y-4"
              >
                {/* Platform name + rank badge */}
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <div className="w-2.5 h-2.5 rounded-full shrink-0" style={{ background: PLATFORM_COLORS[rec.platform] || "#9CA3AF" }} />
                    <span className="font-semibold text-foreground text-sm">{rec.platform}</span>
                  </div>
                  <span className={`text-[10px] uppercase tracking-wider font-semibold px-2 py-0.5 rounded-full ${RANK_STYLES[rec.rank]}`}>
                    {rec.rank}
                  </span>
                </div>

                {/* Allocation percentage as a big number */}
                <div>
                  <div className="text-3xl font-bold text-foreground tabular-nums">
                    {rec.allocation_pct}%
                  </div>
                  <div className="text-xs text-muted-foreground mt-0.5">
                    ${rec.budget_usd.toLocaleString()} / month
                  </div>
                </div>

                {/* Visual allocation bar */}
                <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                  <div
                    className="h-full rounded-full"
                    style={{
                      width: `${rec.allocation_pct}%`,
                      background: PLATFORM_COLORS[rec.platform] || "#9CA3AF",
                    }}
                  />
                </div>

                {/* Key platform metrics from the pipeline data */}
                <div className="grid grid-cols-3 gap-2 py-2 border-t border-border">
                  <div className="text-center">
                    <div className="text-xs text-muted-foreground uppercase tracking-wider">CTR</div>
                    <div className="text-sm font-semibold text-foreground tabular-nums">
                      {PLATFORM_DATA[rec.platform].avg_ctr_pct.toFixed(2)}%
                    </div>
                  </div>
                  <div className="text-center border-x border-border">
                    <div className="text-xs text-muted-foreground uppercase tracking-wider">CPM</div>
                    <div className="text-sm font-semibold text-foreground tabular-nums">
                      ${PLATFORM_DATA[rec.platform].cpm_median.toFixed(0)}
                    </div>
                  </div>
                  <div className="text-center">
                    <div className="text-xs text-muted-foreground uppercase tracking-wider">ROAS</div>
                    <div className="text-sm font-semibold text-foreground tabular-nums">
                      {PLATFORM_DATA[rec.platform].avg_roas.toFixed(1)}x
                    </div>
                  </div>
                </div>

                {/* Plain-English reason for this allocation */}
                <p className="text-xs text-muted-foreground leading-relaxed">
                  {rec.reason}
                </p>
              </div>
            ))}
          </div>

          {/* How the recommendation was made - full transparency section */}
          <div className="surface-card rounded-xl p-5">
            <div className="flex items-center gap-2 mb-4">
              <TrendingUp className="w-4 h-4 text-muted-foreground" />
              <h3 className="text-sm font-semibold text-foreground">How this recommendation was calculated</h3>
            </div>

            <div className="space-y-2.5">
              {/* One row per platform showing the exact score that drove the ranking */}
              {result.map((rec) => (
                <div key={rec.platform} className="flex items-start gap-3">
                  <div className="w-2 h-2 rounded-full mt-1.5 shrink-0" style={{ background: PLATFORM_COLORS[rec.platform] || "#9CA3AF" }} />
                  <div>
                    <span className="text-xs font-semibold text-foreground">{rec.platform}: </span>
                    <span className="text-xs text-muted-foreground">{rec.score_label}</span>
                  </div>
                </div>
              ))}
            </div>

            {/* Explain which metric was used for the goal */}
            <div className="mt-4 p-3 bg-muted/40 rounded-lg">
              <p className="text-xs text-muted-foreground leading-relaxed">
                {goal === "awareness"   && "For brand awareness, platforms were ranked by their CTR divided by CPM. This measures how many clicks you get per dollar of impression cost - a higher ratio means better reach value."}
                {goal === "conversions" && "For conversions, platforms were ranked by their average ROAS (Return on Ad Spend). A higher ROAS means each dollar spent returns more revenue."}
                {goal === "traffic"     && "For website traffic, platforms were ranked by their average CTR. A higher CTR means a larger share of people who saw the ad actually clicked it."}
              </p>
            </div>
          </div>

          {/* Privacy note at the bottom */}
          <div className="flex items-start gap-3 p-4 rounded-xl border border-emerald-200 bg-emerald-50">
            <Shield className="w-4 h-4 text-emerald-600 mt-0.5 shrink-0" />
            <p className="text-xs text-emerald-700 leading-relaxed">
              All platform metrics shown here are aggregated across a minimum of 3 anonymized clients (k-anonymity = 3).
              No individual client data is exposed. The numbers come from the cross-client portfolio pipeline
              built as part of this project.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

