import fs from "fs";
import path from "path";
import KPICards from "@/components/kpi-cards";
import PlatformEfficiency from "@/components/platform-efficiency";
import DataHealthCard from "@/components/data-health-card";
import ArchitectureDiagram from "@/components/architecture-diagram";
import { Database, Shuffle, AlertTriangle, Users, BarChart3 } from "lucide-react";

type Overview = {
  kpis: {
    total_spend: number;
    total_impressions: number;
    avg_ctr_pct: number;
    total_conversions: number;
    avg_roas: number;
  };
  platform_efficiency: Array<{
    platform: string;
    total_spend: number;
    total_impressions: number;
    total_conversions: number;
    avg_ctr_pct: number;
    avg_cpm: number;
    avg_cpc: number;
    avg_roas: number;
    avg_cpa: number;
  }>;
  data_health: {
    total_rows: number;
    clean_rows: number;
    flagged_rows: number;
    pct_flagged: number;
    status: "HEALTHY" | "WARNING" | "CRITICAL";
    flag_breakdown: Array<{ flag_type: string; count: number }>;
  };
};

/*
  Reads overview.json from the public/data folder at build time.
  This file is generated by the Python pipeline scripts before the
  Next.js app is started, so it always reflects the latest run.
*/
async function loadOverview(): Promise<Overview> {
  const filePath = path.join(process.cwd(), "public", "data", "overview.json");
  const file = await fs.promises.readFile(filePath, "utf-8");
  return JSON.parse(file);
}

/*
  The five pipeline stages shown in the "How It Works" section.
  Each step maps to a script in the scripts/ folder of this project.
*/
const PIPELINE_STEPS = [
  {
    icon: Database,
    step: "01",
    title: "Raw Platform Exports",
    desc: "Three separate CSVs styled like real exports from Meta, Google, and TikTok. Each has different column names, date formats, and injected errors.",
  },
  {
    icon: Shuffle,
    step: "02",
    title: "Schema Unification",
    desc: "Column mapping dictionaries normalize every platform into one clean schema: same column names, same date format, same currency unit.",
  },
  {
    icon: AlertTriangle,
    step: "03",
    title: "Automated Error Flagging",
    desc: "Five checks run on every row: clicks exceeding impressions, negative values, missing critical fields, CPM spikes above 5x rolling average, and duplicates.",
  },
  {
    icon: Users,
    step: "04",
    title: "Multi-Client Anonymization",
    desc: "Each row is assigned to Client A, B, or C based on country groupings. No country names are stored - only the anonymous client ID.",
  },
  {
    icon: BarChart3,
    step: "05",
    title: "Portfolio Intelligence",
    desc: "Cross-client insights are generated with k-anonymity enforced: no metric is published unless it draws from at least 3 distinct clients.",
  },
];

/*
  The overview page is a server component. It reads the JSON data file
  on the server at request time and passes the data down to child components.
  No API call or loading state needed.
*/
export default async function Home() {
  const data = await loadOverview();

  return (
    <div className="max-w-7xl mx-auto space-y-12">

      {/* Page header */}
      <div className="space-y-3">
        <div className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">
          Performance Overview
        </div>
        <h1 className="text-4xl md:text-5xl font-semibold tracking-tight text-foreground">
          Unified ad data across{" "}
          <span className="text-gradient">Meta, Google, TikTok</span>
        </h1>
        <p className="text-base text-muted-foreground max-w-2xl leading-relaxed">
          A working prototype that ingests messy multi-platform ad exports,
          standardizes them into one schema, flags data quality issues automatically,
          and generates privacy-safe cross-client portfolio insights.
        </p>
      </div>

      {/* How it works - pipeline overview */}
      <section className="space-y-5">
        <div>
          <h2 className="text-xl font-semibold text-foreground">How It Works</h2>
          <p className="text-sm text-muted-foreground mt-1.5">
            Five pipeline stages transform raw, messy exports into actionable insights.
          </p>
        </div>

        {/* Five steps in a horizontal scrollable row */}
        <div className="grid grid-cols-1 md:grid-cols-5 gap-3">
          {PIPELINE_STEPS.map((s, idx) => {
            const Icon = s.icon;
            return (
              <div key={s.step} className="relative">

                {/* Arrow connector between steps (hidden on mobile) */}
                {idx < PIPELINE_STEPS.length - 1 && (
                  <div className="hidden md:block absolute right-0 top-1/2 -translate-y-1/2 translate-x-1/2 z-10">
                    <div className="w-3 h-3 border-t-2 border-r-2 border-border rotate-45" />
                  </div>
                )}

                <div className="surface-card rounded-xl p-4 h-full">
                  {/* Step number and icon */}
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-xs font-mono text-primary font-bold">{s.step}</span>
                    <Icon className="w-4 h-4 text-primary" />
                  </div>
                  <div className="text-base font-semibold text-foreground mb-1.5">{s.title}</div>
                  <p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* KPI headline numbers */}
      <section className="space-y-4">
        <div>
          <h2 className="text-xl font-semibold text-foreground">Portfolio at a Glance</h2>
          <p className="text-sm text-muted-foreground mt-1.5">
            Aggregated metrics across all platforms after data cleaning and deduplication.
          </p>
        </div>
        <KPICards kpis={data.kpis} />
      </section>

      {/* Platform efficiency comparison table */}
      <section className="space-y-4">
        <div>
          <h2 className="text-xl font-semibold text-foreground">Platform Efficiency</h2>
          <p className="text-sm text-muted-foreground mt-1.5">
            Cost and return metrics per platform. Green = best for that metric. Red = worst.
            CTR and ROAS are better when higher. CPM, CPC, and CPA are better when lower.
          </p>
        </div>
        <PlatformEfficiency rows={data.platform_efficiency} />
      </section>

      {/* Data quality summary */}
      <section className="space-y-4">
        <div>
          <h2 className="text-xl font-semibold text-foreground">Data Quality Report</h2>
          <p className="text-sm text-muted-foreground mt-1.5">
            Results from 5 automated quality checks run on every row in the unified dataset.
            Flagged rows are quarantined and never used in downstream calculations.
          </p>
        </div>
        <DataHealthCard health={data.data_health} />
      </section>

      {/* Architecture / pipeline layer diagram */}
      <section className="space-y-5">
        <div>
          <h2 className="text-xl font-semibold text-foreground">Pipeline Architecture</h2>
          <p className="text-sm text-muted-foreground mt-1.5">
            End-to-end data flow from raw platform exports through to the two dashboard outputs.
          </p>
        </div>
        <ArchitectureDiagram />
      </section>
    </div>
  );
}
