import fs from "fs";
import path from "path";
import { Lock, Shield } from "lucide-react";
import PortfolioKPIs from "@/components/portfolio-kpis";
import CTRChart from "@/components/ctr-chart";
import SpendShareChart from "@/components/spend-share-chart";
import CPMRanges from "@/components/cpm-ranges";
import KAnonymityTable from "@/components/k-anonymity-table";
import ROASTrendChart from "@/components/roas-trend-chart";

type MonthlyRow = {
  month: string;
  platform: string;
  avg_roas: number;
  total_spend: number;
  client_count: number;
};

type Insights = {
  portfolio_kpis: {
    total_spend: number;
    total_impressions: number;
    total_clicks: number;
    total_conversions: number;
    avg_roas: number;
    avg_ctr_pct: number;
    avg_cpm: number;
    client_count: number;
  };
  avg_ctr_by_platform: Array<{ platform: string; avg_ctr_pct: number; client_count: number }>;
  cpm_ranges_by_platform: Array<{
    platform: string;
    cpm_min: number; cpm_p25: number; cpm_median: number; cpm_p75: number; cpm_max: number;
    client_count: number;
  }>;
  spend_share_by_platform: Array<{
    platform: string; total_spend: number; spend_share_pct: number; client_count: number;
  }>;
  monthly_platform_roas: MonthlyRow[];
};

/*
  Reads portfolio_insights.json from public/data at build time.
  This file is generated by scripts/06_portfolio_insights.py
  and contains all k-anonymity-verified cross-client metrics.
*/
async function loadInsights(): Promise<Insights> {
  const filePath = path.join(process.cwd(), "public", "data", "portfolio_insights.json");
  const file = await fs.promises.readFile(filePath, "utf-8");
  return JSON.parse(file);
}

/*
  The portfolio page shows aggregated cross-client insights.
  All metrics here passed k-anonymity verification: each one
  was computed from at least 3 distinct client IDs.
*/
export default async function PortfolioPage() {
  const data = await loadInsights();

  return (
    <div className="max-w-7xl mx-auto space-y-12">

      {/* Page header */}
      <div className="space-y-3">
        <div className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">
          Cross-Client Aggregated Insights
        </div>
        <h1 className="text-3xl md:text-4xl font-semibold tracking-tight text-foreground">
          Portfolio insights,{" "}
          <span className="text-gradient">anonymized by design</span>
        </h1>
        <p className="text-sm text-muted-foreground max-w-2xl leading-relaxed">
          Aggregated metrics pooled across {data.portfolio_kpis.client_count} anonymized clients.
          Every metric shown here was verified to include data from at least 3 distinct clients
          before being published. No individual client can be reverse-engineered from these numbers.
        </p>
      </div>

      {/* Privacy enforcement banner */}
      <div className="flex items-start gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4">
        <div className="mt-0.5 w-8 h-8 rounded-lg bg-emerald-100 flex items-center justify-center shrink-0">
          <Shield className="w-4 h-4 text-emerald-600" />
        </div>
        <div className="text-sm">
          <div className="font-semibold text-emerald-800">K-Anonymity Enforced (k=3)</div>
          <div className="text-emerald-700 mt-1 leading-relaxed text-xs">
            No individual client identifiers are stored. Clients are referred to only as
            Client A, Client B, and Client C. Any aggregated metric drawing from fewer than
            3 distinct clients is automatically suppressed and never shown anywhere in the app.
          </div>
        </div>
      </div>

      {/* Portfolio headline KPIs */}
      <section className="space-y-4">
        <div>
          <h2 className="text-xl font-semibold text-foreground">Portfolio KPIs</h2>
          <p className="text-sm text-muted-foreground mt-1">
            Combined totals and averages across all 3 clients and all 3 platforms.
          </p>
        </div>
        <PortfolioKPIs kpis={data.portfolio_kpis} />
      </section>

      {/* ROAS trend over time - the most important new chart */}
      <section className="space-y-4">
        <div>
          <h2 className="text-xl font-semibold text-foreground">ROAS Trend by Platform (2024)</h2>
          <p className="text-sm text-muted-foreground mt-1">
            How the return on every dollar spent changed month by month across each platform.
            A rising line means the platform is becoming more efficient over time.
          </p>
        </div>
        <ROASTrendChart data={data.monthly_platform_roas} />
      </section>

      {/* CTR and spend share side by side */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

        <section className="space-y-4">
          <div>
            <h2 className="text-xl font-semibold text-foreground">Avg CTR by Platform</h2>
            <p className="text-sm text-muted-foreground mt-1">
              Out of every 100 people who saw the ad, how many clicked it.
            </p>
          </div>
          <CTRChart data={data.avg_ctr_by_platform} />
        </section>

        <section className="space-y-4">
          <div>
            <h2 className="text-xl font-semibold text-foreground">Portfolio Spend Distribution</h2>
            <p className="text-sm text-muted-foreground mt-1">
              How the total budget across all 3 clients is split between platforms.
            </p>
          </div>
          <SpendShareChart data={data.spend_share_by_platform} />
        </section>
      </div>

      {/* CPM range distribution */}
      <section className="space-y-4">
        <div>
          <h2 className="text-xl font-semibold text-foreground">CPM Range Distribution</h2>
          <p className="text-sm text-muted-foreground mt-1">
            The cost to reach 1,000 people on each platform, showing the full
            range from cheapest to most expensive. A narrower range means more
            predictable pricing.
          </p>
        </div>
        <CPMRanges data={data.cpm_ranges_by_platform} />
      </section>

      {/* Privacy audit log at the bottom */}
      <section className="space-y-4">
        <div className="flex items-center gap-2">
          <Lock className="w-4 h-4 text-muted-foreground" />
          <h2 className="text-xl font-semibold text-foreground">Privacy Audit Log</h2>
        </div>
        <p className="text-sm text-muted-foreground">
          An auditable record showing exactly how many clients contributed to each insight
          and whether it passed the k=3 threshold required for publication.
        </p>
        <KAnonymityTable insights={data} />
      </section>
    </div>
  );
}

